---
# Gerenciamento de pacotes e atualização

- name: Atualizacao do vim (posso colocar asterisco para todo SO)
  yum: name=vim state=latest update_cache=yes

- name: Instacao de pacotes
  yum: 
    name: "{{ packages }}"
    state: latest
  vars:
   packages:
    - net-tools
    - vim 

#- name: Configurando Timezone
#  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

...