---
# Gerenciamento de pacotes e atualização

- name: Atualizacao do vim (posso colocar name=asterisco para todo SO)
  yum: name=vim state=latest update_cache=yes

- name: Instacao de pacotes
  yum: 
    name: "{{ packages }}"
    state: latest
  vars:
   packages:
    - vim

#- name: Configurando Timezone
#  file: src=/usr/share/zoneinfo/America/Sao_Paulo dest=/etc/localtime state=link force=yes

# Copia de arquivos
- name: Copiando arquivo de backup
  copy: src=backup.teste dest=/tmp/backup.teste

# Copia de tamplate
- name: Copiando um template
  template: src=motd dst=/tmp/motd force=yes owner=root group=root

# Instalação do git
- name: Instalacao Git
  yum: git state=latest
  notify: Restart git



...